//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalChart
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_Teeth
    {
        public int PatientTeethId { get; set; }
        public int PatientID_fk { get; set; }
        public int TeethID_fk { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Tooth Tooth { get; set; }
    }
}
