//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalChart
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Patient_Teeth = new HashSet<Patient_Teeth>();
        }
    
        public int PatientID { get; set; }
        public string PatientFN { get; set; }
        public string PatientLN { get; set; }
        public Nullable<int> PatientAge { get; set; }
        public Nullable<System.DateTime> PatientBirthday { get; set; }
        public string PatientSex { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patient_Teeth> Patient_Teeth { get; set; }
    }
}
