//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalChart
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tooth
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tooth()
        {
            this.Patient_Teeth = new HashSet<Patient_Teeth>();
        }
    
        public int TeethID { get; set; }
        public Nullable<int> Teethnumber { get; set; }
        public string TeethLeft { get; set; }
        public string TeethRight { get; set; }
        public string TeethTop { get; set; }
        public string TeethBottom { get; set; }
        public string TeethCheck { get; set; }
        public string TeethEx { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patient_Teeth> Patient_Teeth { get; set; }
    }
}
